image: docker:19.03.12
services:
  - docker:19.03.12-dind

stages:
  - build
  - deploy


    #build:
    #stage: build
    #script:
    #- ls -lah
      #- apk add --no-cache docker-compose
      #- docker-compose build


deploy-to-remote-server:
  stage: deploy
  #  image: alpine
  #before_script:
  #  - apk add openssh-client
  #  - eval $(ssh-agent -s)
  #  - mkdir -p ~/.ssh
  #  - chmod 700 ~/.ssh
  before_script:
    - apk add openssh-client
     # Setup SSH deploy keys
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo $SSH_PRIVATE_KEY)
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    

  script:
    - echo "ssh and deploying to remote server"
    - apk update && apk add openssh && apk add sshpass
    - sshpass -V
      #- export SSHPASS=$DEPLOY_PASS
      #- sshpass -e ssh -oStrictHostKeyChecking=no fiverr@185.239.237.190 "cd /home/fiverr/w2do/ && git pull && bash code-deploy-remote.sh"
    - ssh fiverr@185.239.237.190 "cd /home/fiverr/w2do/ && git pull && bash code-deploy-remote.sh"
    #- bash code-deploy-remote.sh

  only:
    - master
