image: docker:19.03.12
services:
  - docker:19.03.12-dind

stages:
  - build
  - deploy


build:
  stage: build
  script:
    - ls -lah
      #- apk add --no-cache docker-compose
      #- docker-compose build


deploy-to-remote-server:
  stage: deploy
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

  script:
    - echo "ssh and deploying to remote server"
    - apk update && apk add openssh && apk add sshpass
    - sshpass -p "$DEPLOY_PASS" ssh -t -t -oStrictHostKeyChecking=no fiverr@"$DEPLOY_IP" -p "$DEPLOY_PORT" "cd /home/fiverr/w2do/; bash code-deploy-remote.sh"
    #- bash code-deploy-remote.sh

  only:
    - master
