version: '3.4'
services:
  frontend:
    build: .
    ports:
      - '8080:80'
  backend:
    build: server
    ports:
      - '3000:3000'

    links:
      - database

  database:
    image: mongo:latest
    ports:
      - '27018:27017'
    volumes:
      - "./database:/data/db"
