version: "3"
services:
  api:
    build: ./server
    ports:
      - "8085:8085"
    depends_on:
      - db
    container_name: todo-api

  client:
    build: .
    ports:
      - "85:85"
    container_name: todo-client

  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: todo-db
